#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=debugq
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=20
#SBATCH --time=1:00:00
#SBATCH --output=./out/slurm-%j.out

#python3 ./out/script24.py >> ./out/output24.txt &
#python3 ./out/script25.py >> ./out/output25.txt &
#python3 ./out/script26.py >> ./out/output26.txt &
#python3 ./out/script27.py >> ./out/output27.txt &
python3 ./out/script28.py >> ./out/output28.txt &
python3 ./out/script29.py >> ./out/output29.txt &
python3 ./out/script30.py >> ./out/output30.txt &
python3 ./out/script31.py >> ./out/output31.txt &
wait
