#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=debugq
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=20
#SBATCH --time=1:00:00
#SBATCH --output=./out/slurm-%j.out

#python3 ./out/script16.py >> ./out/output16.txt &
#python3 ./out/script17.py >> ./out/output17.txt &
#python3 ./out/script18.py >> ./out/output18.txt &
#python3 ./out/script19.py >> ./out/output19.txt &
python3 ./out/script20.py >> ./out/output20.txt &
python3 ./out/script21.py >> ./out/output21.txt &
python3 ./out/script22.py >> ./out/output22.txt &
python3 ./out/script23.py >> ./out/output23.txt &
wait
